name: publish

env:
  NODE_VERSION: 18.x
  NPM_REGISTRY: 'https://registry.npmjs.org'

on:
  push:
    tags:
      - v*

jobs:
  macos-builds:
    name: Builds (macOS)
    strategy:
      matrix:
        target: [darwin-x64, darwin-arm64]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build
        uses: neon-actions/build@v0.3.2
        with:
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: true

  windows-builds:
    name: Builds (Windows)
    strategy:
      matrix:
        target: [win32-x64-msvc, win32-arm64-msvc]
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build
        uses: neon-actions/build@v0.3.2
        with:
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: true

  other-builds:
    name: Builds (other platforms)
    strategy:
      matrix:
        target: [linux-x64-gnu, linux-arm-gnueabihf, android-arm-eabi]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build
        uses: neon-actions/build@v0.3.2
        with:
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          use-cross: true
          npm-publish: false
          github-release: true

  publish:
    name: Publish
    needs: [macos-builds, windows-builds, other-builds]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY }}
          cache: npm
      - name: Setup
        shell: bash
        run: npm i
      - name: Publish
        uses: neon-actions/publish@v0.4.1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY }}
          fetch-binaries: "*.tgz"
          github-release: true
